"use client";

import { Suspense, useEffect, useMemo, useRef, useState } from "react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { FolderKanban, Loader2 } from "lucide-react";

import { AppShell } from "@/components/dashboard/app-shell";
import { Button } from "@/components/ui/button";
import { SelectMenu } from "@/components/ui/select-menu";
import { ReportList } from "@/components/reports/report-list";
import { ReportView } from "@/components/reports/report-view";
import type { ReportWithProvenance } from "@/components/reports/report-data";
import {
  downloadReportPdf, fetchBundle, fetchOfficialReports, fetchProjects, fetchReport, fetchRuns, generateOfficialReport, type ProjectItem,
} from "@/lib/api";
import { useAnalysis } from "@/hooks/use-analysis";
import { useAuth } from "@/hooks/use-auth";
import type { FrontendBundle, RunSummary } from "@/types";

function ReportsView() {
  const params = useSearchParams();
  // Real reports: one per pipeline run, generated by the backend from that run's artefacts.
  const [runs, setRuns] = useState<RunSummary[]>([]);
  const [liveReports, setLiveReports] = useState<ReportWithProvenance[] | null>(null);
  useEffect(() => {
    let cancelled = false;
    fetchRuns()
      .then((rs) => {
        if (!cancelled) setRuns(rs);
        return Promise.all(rs.map((r) => fetchReport(r.studyAreaId, r.runId).catch(() => null)));
      })
      .then((rs) => {
        if (!cancelled) setLiveReports(rs.filter((r): r is ReportWithProvenance => r !== null));
      })
      .catch(() => {
        if (!cancelled) setLiveReports(null);
      });
    return () => {
      cancelled = true;
    };
  }, []);
  const { sceneId, runId } = useAnalysis();
  const { can } = useAuth();
  const [official, setOfficial] = useState<ReportWithProvenance[]>([]);
  const [projects, setProjects] = useState<ProjectItem[]>([]);
  const [projectId, setProjectId] = useState<number | "">("");
  const [generating, setGenerating] = useState(false);
  useEffect(() => {
    fetchOfficialReports().then(setOfficial).catch(() => setOfficial([]));
    fetchProjects().then(setProjects).catch(() => setProjects([]));
  }, []);
  const reports = useMemo(() => [...official, ...(liveReports ?? [])], [official, liveReports]);
  const loading = liveReports === null && official.length === 0;
  const generate = async () => {
    setGenerating(true);
    try {
      const rep = await generateOfficialReport(sceneId, runId, projectId === "" ? undefined : projectId);
      setOfficial((o) => [rep, ...o]);
      setActiveId(rep.id);
    } catch (e) {
      window.alert(`Report generation failed: ${e instanceof Error ? e.message : String(e)}`);
    } finally {
      setGenerating(false);
    }
  };
  const [activeId, setActiveId] = useState(params.get("id") ?? "");
  const [downloading, setDownloading] = useState(false);

  // default: the run the dashboard is showing (stored LATEST unless the user picked another), not simply the newest -
  // newest can be a near-real-time satellite run
  const dashboardRunId = runId === "latest" ? runs.find((r) => r.studyAreaId === sceneId && r.isLatest)?.runId : runId;
  const report = useMemo(() => reports.find((r) => r.id === activeId)
    ?? reports.find((r) => (r as ReportWithProvenance).provenance?.runId === dashboardRunId) ?? reports[0] ?? null, [reports, activeId, dashboardRunId]);
  const reportRunId = report?.provenance?.runId;
  const run = runs.find((r) => r.runId === reportRunId);

  // The run's network + what-if artefact feed the scenario animation (cached per run).
  const bundles = useRef(new Map<string, FrontendBundle | null>());
  const [bundle, setBundle] = useState<{ key: string; data: FrontendBundle | null } | null>(null);
  const bundleKey = report && reportRunId ? `${report.sceneId}/${reportRunId}` : "";
  useEffect(() => {
    if (!bundleKey) return;
    const cached = bundles.current.get(bundleKey);
    if (cached !== undefined) { setBundle({ key: bundleKey, data: cached }); return; }
    let cancelled = false;
    const [scene, rid] = bundleKey.split("/");
    fetchBundle(scene, rid)
      .then((b) => b, () => null)
      .then((b) => {
        bundles.current.set(bundleKey, b);
        if (!cancelled) setBundle({ key: bundleKey, data: b });
      });
    return () => { cancelled = true; };
  }, [bundleKey]);
  const current = bundle?.key === bundleKey ? bundle.data : undefined;
  const graphState: "loading" | "ready" | "missing" = !bundleKey ? "missing" : current === undefined ? "loading" : current ? "ready" : "missing";

  // Stored official reports → server-rendered PDF (provenance, network figure, decisions, audit footer).
  // Per-run preview reports are not stored, so they fall back to the browser's print-to-PDF.
  const handleDownload = async () => {
    const m = /^official-(\d+)$/.exec(report?.id ?? "");
    setDownloading(true);
    if (m) {
      try { await downloadReportPdf(Number(m[1])); }
      catch (e) { window.alert(e instanceof Error ? e.message : String(e)); }
      finally { setDownloading(false); }
      return;
    }
    window.setTimeout(() => {
      setDownloading(false);
      window.print();
    }, 900);
  };

  const projectOptions = [
    { value: "", label: "No project" },
    ...projects.filter((p) => p.study_area_id === sceneId).map((p) => ({ value: String(p.id), label: p.name })),
  ];

  return (
    <AppShell
      title="Reports"
      subtitle={reports.length ? "Each analysis run, explained in plain words" : loading ? "Loading reports…" : "No reports yet — run an analysis first"}
      actions={
        can("generate_report") ? (
          <div className="flex items-center gap-2">
            {projectOptions.length > 1 && (
              <SelectMenu className="hidden md:block" label="Project" icon={FolderKanban} value={projectId === "" ? "" : String(projectId)} options={projectOptions} align="right"
                onChange={(v) => setProjectId(v === "" ? "" : Number(v))} />
            )}
            <Button size="sm" onClick={generate} disabled={generating}>{generating ? "Generating…" : "Generate official report"}</Button>
          </div>
        ) : undefined
      }
    >
      <div className="mx-auto grid max-w-[1400px] gap-5 lg:grid-cols-[264px_minmax(0,1fr)]">
        <aside className="scroll-slim pr-1 print:hidden lg:sticky lg:top-6 lg:max-h-[calc(100vh-6rem)] lg:overflow-y-auto">
          {loading ? (
            <div className="flex items-center gap-2 p-3 text-[13px] text-[#64748b]"><Loader2 className="h-4 w-4 animate-spin" />Loading…</div>
          ) : (
            <ReportList reports={reports} activeId={report?.id} onSelect={setActiveId} detail={(r) => {
              const rs = runs.find((x) => x.runId === (r as ReportWithProvenance).provenance?.runId);
              if (!rs) return undefined;
              return [rs.satellite ? `Satellite NRT${rs.satellite.reliability === "unreliable" ? " · model unreliable here" : ""}` : null,
                rs.sceneYear ? `Image ${rs.sceneYear}` : null, `${rs.nPatches} patches`, rs.ecaPctOfHabitat !== undefined ? `${Math.round(rs.ecaPctOfHabitat)}% connected` : null].filter(Boolean).join(" · ");
            }} />
          )}
        </aside>

        {!report && !loading && (
          <div className="rounded-2xl border border-black/[0.06] bg-white p-8 text-[14px] text-[#475569]">
            No report to show yet. Reports are made from real analysis runs — start one in{" "}
            <Link href="/upload" className="font-semibold text-[#15803d] underline">New Analysis</Link>.
          </div>
        )}
        {report && (
          <ReportView
            report={report}
            graph={current?.graph ?? null}
            whatIf={current?.whatIfExample ?? null}
            graphState={graphState}
            downloading={downloading}
            onDownload={handleDownload}
            sceneYear={run?.sceneYear ?? undefined}
          />
        )}
      </div>
    </AppShell>
  );
}

export default function ReportsPage() {
  return (
    <Suspense
      fallback={
        <div className="grid min-h-screen place-items-center bg-background">
          <Loader2 className="h-6 w-6 animate-spin text-[#15803d]" />
        </div>
      }
    >
      <ReportsView />
    </Suspense>
  );
}
