"""baseline schema (pre-Alembic create_all)

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-28 00:13:08.944133
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_baseline'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('old_state', sa.JSON(), nullable=True),
    sa.Column('new_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ts', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('encoder', sa.String(), nullable=True),
    sa.Column('input_bands', sa.JSON(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('result_label', sa.String(), nullable=True),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('n_train', sa.Integer(), nullable=True),
    sa.Column('n_val', sa.Integer(), nullable=True),
    sa.Column('n_test', sa.Integer(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('calibration', sa.JSON(), nullable=True),
    sa.Column('trained_at', sa.String(), nullable=True),
    sa.Column('hardware', sa.JSON(), nullable=True),
    sa.Column('card', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_areas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('protection', sa.String(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lon', sa.Float(), nullable=True),
    sa.Column('min_lat', sa.Float(), nullable=True),
    sa.Column('min_lon', sa.Float(), nullable=True),
    sa.Column('max_lat', sa.Float(), nullable=True),
    sa.Column('max_lon', sa.Float(), nullable=True),
    sa.Column('footprint_km2', sa.Float(), nullable=True),
    sa.Column('primary_habitat', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('label_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('licence', sa.String(), nullable=True),
    sa.Column('supervision', sa.String(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('label_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_label_sources_study_area_id'), ['study_area_id'], unique=False)

    op.create_table('scenes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('date_range', sa.JSON(), nullable=True),
    sa.Column('bands', sa.JSON(), nullable=True),
    sa.Column('sensors', sa.JSON(), nullable=True),
    sa.Column('crs', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_study_area_id'), ['study_area_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('analysis_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('scene_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('result_kind', sa.String(), nullable=True),
    sa.Column('result_label', sa.String(), nullable=True),
    sa.Column('scene_year', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('mmu_ha', sa.Float(), nullable=True),
    sa.Column('tau_km', sa.Float(), nullable=True),
    sa.Column('k', sa.Integer(), nullable=True),
    sa.Column('metric', sa.String(), nullable=True),
    sa.Column('n_patches', sa.Integer(), nullable=True),
    sa.Column('n_edges', sa.Integer(), nullable=True),
    sa.Column('n_components', sa.Integer(), nullable=True),
    sa.Column('habitat_area_ha', sa.Float(), nullable=True),
    sa.Column('landscape_area_ha', sa.Float(), nullable=True),
    sa.Column('iic', sa.Float(), nullable=True),
    sa.Column('pc', sa.Float(), nullable=True),
    sa.Column('eca_ha', sa.Float(), nullable=True),
    sa.Column('eca_pct', sa.Float(), nullable=True),
    sa.Column('interface_score', sa.Float(), nullable=True),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('manifest', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_versions_study_area_id'), ['study_area_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_study_area_id'), ['study_area_id'], unique=False)

    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_detections_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_detections_study_area_id'), ['study_area_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('priority_patches', sa.JSON(), nullable=True),
    sa.Column('candidates', sa.JSON(), nullable=True),
    sa.Column('responsible', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_study_area_id'), ['study_area_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_study_area_id'), ['study_area_id'], unique=False)

    op.create_table('field_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('detection_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('evidence_required', sa.String(), nullable=True),
    sa.Column('assignee_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_tasks_study_area_id'), ['study_area_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.String(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(), nullable=True),
    sa.Column('verification', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['field_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_task_id'))

    op.drop_table('evidence')
    op.drop_table('reports')
    with op.batch_alter_table('field_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_tasks_study_area_id'))

    op.drop_table('field_tasks')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenarios_study_area_id'))

    op.drop_table('scenarios')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_study_area_id'))

    op.drop_table('projects')
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_detections_study_area_id'))
        batch_op.drop_index(batch_op.f('ix_detections_run_id'))

    op.drop_table('detections')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_study_area_id'))

    op.drop_table('alerts')
    with op.batch_alter_table('analysis_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_versions_study_area_id'))

    op.drop_table('analysis_versions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scenes_study_area_id'))

    op.drop_table('scenes')
    with op.batch_alter_table('label_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_label_sources_study_area_id'))

    op.drop_table('label_sources')
    op.drop_table('study_areas')
    op.drop_table('organizations')
    op.drop_table('models')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
