"""model registry status ladder

Revision ID: 0003_model_registry
Revises: 0002_jobs_artifacts
Create Date: 2026-09-28 00:23:32.224487
"""
from alembic import op
import sqlalchemy as sa


revision = '0003_model_registry'
down_revision = '0002_jobs_artifacts'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('display_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('code_commit', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('validation', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('status_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_models_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_models_status'))
        batch_op.drop_column('status_updated_at')
        batch_op.drop_column('validation')
        batch_op.drop_column('code_commit')
        batch_op.drop_column('version')
        batch_op.drop_column('display_name')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
