"""restoration reviews, disagreements, checklist

Revision ID: 0004_phase5_workflow
Revises: 0003_model_registry
Create Date: 2026-09-28 00:47:13.615112
"""
from alembic import op
import sqlalchemy as sa


revision = '0004_phase5_workflow'
down_revision = '0003_model_registry'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restoration_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('model_recommendation', sa.JSON(), nullable=True),
    sa.Column('gis_review', sa.JSON(), nullable=True),
    sa.Column('field_task_id', sa.Integer(), nullable=True),
    sa.Column('feasibility', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['field_task_id'], ['field_tasks.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restoration_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_restoration_reviews_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_restoration_reviews_study_area_id'), ['study_area_id'], unique=False)

    op.create_table('model_disagreements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=True),
    sa.Column('study_area_id', sa.String(), nullable=True),
    sa.Column('run_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('object_type', sa.String(), nullable=True),
    sa.Column('object_id', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.String(), nullable=True),
    sa.Column('model_prediction', sa.JSON(), nullable=True),
    sa.Column('field_observation', sa.JSON(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['analysis_versions.id'], ),
    sa.ForeignKeyConstraint(['study_area_id'], ['study_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evidence_id')
    )
    with op.batch_alter_table('model_disagreements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_disagreements_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_disagreements_study_area_id'), ['study_area_id'], unique=False)

    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_column('checklist')

    with op.batch_alter_table('model_disagreements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_disagreements_study_area_id'))
        batch_op.drop_index(batch_op.f('ix_model_disagreements_status'))

    op.drop_table('model_disagreements')
    with op.batch_alter_table('restoration_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_restoration_reviews_study_area_id'))
        batch_op.drop_index(batch_op.f('ix_restoration_reviews_run_id'))

    op.drop_table('restoration_reviews')
    # ### end Alembic commands ###
